### ISSUE TITLE
Unable to find steam installation (Ubuntu 20.04)

### ISSUE THREAD

**Issue by CStafford-14** [zbanks/CrewLink#2]
![crewlink_err](https://user-images.githubusercontent.com/35039669/103095415-890f6880-45ce-11eb-83db-ff6ebb826e9e.png)
Steam is running, but I normally don't use steam to run the game as Proton doesn't work on 20.04. I normally use Lutris.
And yes, Among Us is installed through steam.

**Comment by CStafford-14** [comment]
![crewlink_terminal](https://user-images.githubusercontent.com/35039669/103095544-ee635980-45ce-11eb-9a3c-0d1754c5caa3.png)

New thing... launched Among Us through Lutris and it's complaining about an issue with the Among Us process... once the game, launched, the window now says "MENU" like it should.

**Comment by PassWorld44** [comment]
I got the same error even if i run it with proton

**Comment by mijofa** [comment]
The first section of the README says "Doesn't launch Among Us, so there's no parent process relationship; ptrace security gets in the way"
You need to launch the game yourself from outside CrewLink, rather than pressing the "Open Game" button inside CrewLink.

**Comment by PassWorld44** [comment]
then it just say "waiting for among us"

![Screenshot_20201229_191546](https://user-images.githubusercontent.com/40109852/103305151-abf4af00-4a0a-11eb-8fa4-cc24ccbd5d41.png)

**Comment by dzlandis** [comment]
This seems to be fixed in the latest update on Ubuntu 20.04. You may want to install the new release. They simply just removed this option so you just have to start Among Us normally and then it will detect it.

> ![crewlink_err](https://user-images.githubusercontent.com/35039669/103095415-890f6880-45ce-11eb-83db-ff6ebb826e9e.png)
> Steam is running, but I normally don't use steam to run the game as Proton doesn't work on 20.04. I normally use Lutris.
> And yes, Among Us is installed through steam.
