### ISSUE TITLE
CrewLink v1.2.0

### ISSUE THREAD

**Issue by sixthsurge** [zbanks/CrewLink#4]
CrewLink has updated to v1.2.0 and I think this has broken compatibility between the official server and this fork. When I join a lobby, the green circle showing I'm speaking is red instead, even on my CrewLink instance. Is there any way to fix this on my end, or should I just wait for this fork to update?

**Comment by ghaith** [comment]
I have a running version that i'll push soon and submit a pull request here.
If you're willing to get your hands dirty, it needs updates to [memoryjs](https://github.com/zbanks/memoryjs/pull/1), and the iohook module needs to be changed if you're on Arch Linux (the bundled library does not work, you would need to install libuiohook from the aur and copy /usr/lib/libuiohook.so.0.0.0 to node_modules/iohook/builds/.../uiohook.so)

Other than we only need the hard coded part in GameReader.ts to ignore finding the process from the current state. So basically the current 1.2.0 version would work directly then.

**Comment by ghaith** [comment]
I made a 1.2.0 version [here](https://github.com/ghaith/CrewLink/releases/tag/v1.2.0-alpha). I intend to still submit a pull request to this branch, but if anyone is looking for a quick solution there it is
