### ISSUE TITLE
Unsupported version

### ISSUE THREAD

**Issue by Denton-L** [zbanks/CrewLink#8]
I'm currently getting the following error when I'm launching Crewlink built from source:

![image](https://user-images.githubusercontent.com/9620836/103426178-6d770580-4b6c-11eb-880c-675eb629058c.png)

I suspect the error is because the version has been changed to `v1.2.1-linux`. I think the fix for this is either fixing changing the version back to `v1.2.1` or stripping the `-linux` during the version check.

**Comment by Denton-L** [comment]
cc @zbanks @ghaith

**Comment by Denton-L** [comment]
Sorry, seems like a PEBKAC issue. I'm trying to run the unpacked version which is what's causing these issues. I see that you have a version with `-linux` stripped that's tagged but not on any branch. I'll package that tagged version.

**Comment by zbanks** [comment]
Yeah don't worry, this was my bad (see my comment on #9)
